require 'rubygems'
require 'rake'
require 'rubygems/package_task'

spec_data = File.open('iron_sharepoint.gemspec').read
spec = nil
Thread.new do
  spec = eval("#{spec_data}")
end.join

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/*_test.rb'
  test.verbose = false
end
